//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogsReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogsReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear1 {
            get {
                object obj = ResourceManager.GetObject("clear1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter17 {
            get {
                object obj = ResourceManager.GetObject("filter17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить фильтр во время поиска.
        /// </summary>
        internal static string Form_AlreadyUseFilterComment {
            get {
                return ResourceManager.GetString("Form_AlreadyUseFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по полю &quot;Date&quot;.
        /// </summary>
        internal static string Form_DateFilterComment {
            get {
                return ResourceManager.GetString("Form_DateFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по полю &quot;Trace&quot;. Опция отключается если значение пустое. Несколько фильтров необходимо указать через запятую. Регистр не учитывается..
        /// </summary>
        internal static string Form_MessageFilterComment {
            get {
                return ResourceManager.GetString("Form_MessageFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистр не учитывается. При использовании поиска по Regex - таймаут выполнения 1 секунда..
        /// </summary>
        internal static string Form_SearchComment {
            get {
                return ResourceManager.GetString("Form_SearchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по полю &quot;Trace name&quot;. Опция отключается если значение пустое. Несколько фильтров необходимо указать через запятую. Регистр не учитывается..
        /// </summary>
        internal static string Form_TraceNameLikeComment {
            get {
                return ResourceManager.GetString("Form_TraceNameLikeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по полю &quot;Trace name&quot; на несовпадение. Опция отключается если значение пустое. Несколько фильтров необходимо указать через запятую. Регистр не учитывается..
        /// </summary>
        internal static string Form_TraceNameNotLikeComment {
            get {
                return ResourceManager.GetString("Form_TraceNameNotLikeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать сервера и типы файлов.
        /// </summary>
        internal static string Form_trvMainComment {
            get {
                return ResourceManager.GetString("Form_trvMainComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config &quot;{0}&quot; is incorrect! Moved to &quot;{1}&quot;.
        ///
        ///{2}.
        /// </summary>
        internal static string LRSettings_Deserialize_Ex {
            get {
                return ResourceManager.GetString("LRSettings_Deserialize_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущее значение поиска. .
        /// </summary>
        internal static string LRSettings_PreviousSearchComment {
            get {
                return ResourceManager.GetString("LRSettings_PreviousSearchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save config to path &quot;{0}&quot;.
        ///{1}.
        /// </summary>
        internal static string LRSettings_Serialize_Ex {
            get {
                return ResourceManager.GetString("LRSettings_Serialize_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по регулярному выражению выполняется быстрее. Атрибут &quot;encoding&quot; используется при считывании лог файлов..
        /// </summary>
        internal static string LRSettings_UseRegexComment {
            get {
                return ResourceManager.GetString("LRSettings_UseRegexComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к папке с логами. Поиск файлов происходит по всем директориям..
        /// </summary>
        internal static string LRSettingsScheme_LogsDirectoryComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_LogsDirectoryComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное количество потоков. Если установить значение -1, то количество потоков будет соответствовать количеству обрабатываемых файлов..
        /// </summary>
        internal static string LRSettingsScheme_MaxThreadsComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_MaxThreadsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное количество строк для найденного фрагмента. Весь фрагмент должен парсится паттернами из &quot;TraceParse&quot;..
        /// </summary>
        internal static string LRSettingsScheme_MaxTraceLinesComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_MaxTraceLinesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка по полям: &quot;ID&quot;, &quot;Server&quot;, &quot;TraceName&quot;, &quot;Date&quot;, &quot;File&quot;, &quot;FoundLineID&quot; - номер строки в файле по найденному фрагменту, указывается вместе с Description. Через запятую можно указать несколько полей сортировки, а также использовать операцию desc..
        /// </summary>
        internal static string LRSettingsScheme_OrderByComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_OrderByComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ограничение по количеству строк. Сокращает использование оперативной памяти..
        /// </summary>
        internal static string LRSettingsScheme_RowsLimitCommentComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_RowsLimitCommentComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервера для поиска. Указать через запятую..
        /// </summary>
        internal static string LRSettingsScheme_ServersComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_ServersComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паттерны для считывания параметров. Подбираются сверху вниз, от самого точного, до дефолтного. Необходимо использовать группировки. Регулярное выражение работает только с опциями Singleline и CultureInvariant. Таймаут выполнения - 10 секунд.
        ///        Опциональные паттерны: StartTraceWith и EndTraceWith - улучшают скорость поиска, т.к. определяются точные грани трассировки. Опции можно использовать по отдельности, а также в одной настройке..
        /// </summary>
        internal static string LRSettingsScheme_TraceParseComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_TraceParseComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы файлов, указать через запятую. Производится поиск по содержанию в имени файла включая экстеншн..
        /// </summary>
        internal static string LRSettingsScheme_TypesComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_TypesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reset2 {
            get {
                object obj = ResourceManager.GetObject("reset2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save2 {
            get {
                object obj = ResourceManager.GetObject("save2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
