//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogsReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogsReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear1 {
            get {
                object obj = ResourceManager.GetObject("clear1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter17 {
            get {
                object obj = ResourceManager.GetObject("filter17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string LogsReaderForm_alreadyUseFilter_rightPadding {
            get {
                return ResourceManager.GetString("LogsReaderForm_alreadyUseFilter_rightPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90.
        /// </summary>
        internal static string LogsReaderForm_btnClear_Width {
            get {
                return ResourceManager.GetString("LogsReaderForm_btnClear_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110.
        /// </summary>
        internal static string LogsReaderForm_buttonExport_Width {
            get {
                return ResourceManager.GetString("LogsReaderForm_buttonExport_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string LogsReaderForm_buttonFilter_rightPadding {
            get {
                return ResourceManager.GetString("LogsReaderForm_buttonFilter_rightPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string LogsReaderForm_buttonReset_rightPadding {
            get {
                return ResourceManager.GetString("LogsReaderForm_buttonReset_rightPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reset2 {
            get {
                object obj = ResourceManager.GetObject("reset2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save2 {
            get {
                object obj = ResourceManager.GetObject("save2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of end must be greater than date of start.
        /// </summary>
        internal static string Txt_DataFilter_ErrDate {
            get {
                return ResourceManager.GetString("Txt_DataFilter_ErrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout while executing pattern: &quot;{0}&quot;.
        ///Timeout: {1}
        ///Input data:
        ///{2}.
        /// </summary>
        internal static string Txt_DataTemplate_ErrTimeout {
            get {
                return ResourceManager.GetString("Txt_DataTemplate_ErrTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with filter.
        /// </summary>
        internal static string Txt_Form_AlreadyUseFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_AlreadyUseFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Date&quot; filter.
        /// </summary>
        internal static string Txt_Form_DateFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_DateFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use options of invariant culture and ignoring the case. When Regex option of  search is used timeout of completing is 1 second..
        /// </summary>
        internal static string Txt_Form_SearchComment {
            get {
                return ResourceManager.GetString("Txt_Form_SearchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Trace&quot; filter to find a matching. Option turns off when value is empty. Several filters have to be listed with a comma. Case is ignored..
        /// </summary>
        internal static string Txt_Form_TraceFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_TraceFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;TraceName&quot; filter to find a matching. Option turns off when value is empty. Several filters have to be listed with a comma. Case is ignored..
        /// </summary>
        internal static string Txt_Form_TraceNameFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_TraceNameFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server(s) and type(s) of the files must be chosen..
        /// </summary>
        internal static string Txt_Form_trvMainComment {
            get {
                return ResourceManager.GetString("Txt_Form_trvMainComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        internal static string Txt_Initialization {
            get {
                return ResourceManager.GetString("Txt_Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear [F6].
        /// </summary>
        internal static string Txt_LogsReaderForm_Clear {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string Txt_LogsReaderForm_Contains {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date value is incorrect.
        /// </summary>
        internal static string Txt_LogsReaderForm_DateValueIsIncorrect {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_DateValueIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t match by &quot;TraceParse&quot; patterns.
        /// </summary>
        internal static string Txt_LogsReaderForm_DoesntMatchByPattern {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_DoesntMatchByPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file &quot;{0}&quot;. {1}.
        /// </summary>
        internal static string Txt_LogsReaderForm_ErrExport {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_ErrExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export [Ctrl+S].
        /// </summary>
        internal static string Txt_LogsReaderForm_Export {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        internal static string Txt_LogsReaderForm_Exporting {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files completed:.
        /// </summary>
        internal static string Txt_LogsReaderForm_FilesCompleted_1 {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FilesCompleted_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Txt_LogsReaderForm_FilesCompleted_2 {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FilesCompleted_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter [F7].
        /// </summary>
        internal static string Txt_LogsReaderForm_Filter {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Types.
        /// </summary>
        internal static string Txt_LogsReaderForm_FilteTypes {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FilteTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished in {0}.
        /// </summary>
        internal static string Txt_LogsReaderForm_FinishedIn {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FinishedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs folder.
        /// </summary>
        internal static string Txt_LogsReaderForm_LogsFolder {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_LogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Lines.
        /// </summary>
        internal static string Txt_LogsReaderForm_MaxLines {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_MaxLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Threads.
        /// </summary>
        internal static string Txt_LogsReaderForm_MaxThreads {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_MaxThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filter results found.
        /// </summary>
        internal static string Txt_LogsReaderForm_NoFilterResultsFound {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NoFilterResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs found.
        /// </summary>
        internal static string Txt_LogsReaderForm_NoLogsFound {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NoLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Contains.
        /// </summary>
        internal static string Txt_LogsReaderForm_NotContains {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order By.
        /// </summary>
        internal static string Txt_LogsReaderForm_OrderBy {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall found.
        /// </summary>
        internal static string Txt_LogsReaderForm_OverallFound_1 {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_OverallFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matches.
        /// </summary>
        internal static string Txt_LogsReaderForm_OverallFound_2 {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_OverallFound_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset [F8].
        /// </summary>
        internal static string Txt_LogsReaderForm_Reset {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Limit.
        /// </summary>
        internal static string Txt_LogsReaderForm_RowsLimit {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_RowsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search [F5].
        /// </summary>
        internal static string Txt_LogsReaderForm_Search {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        internal static string Txt_LogsReaderForm_Servers {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        internal static string Txt_LogsReaderForm_Servers2 {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Servers2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop [Esc].
        /// </summary>
        internal static string Txt_LogsReaderForm_Stop {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string Txt_LogsReaderForm_Stopping {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to file &quot;{0}&quot;.
        /// </summary>
        internal static string Txt_LogsReaderForm_SuccessExport {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_SuccessExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        internal static string Txt_LogsReaderForm_Types {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use filter when searching.
        /// </summary>
        internal static string Txt_LogsReaderForm_UseFilterWhenSearching {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_UseFilterWhenSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Regex.
        /// </summary>
        internal static string Txt_LogsReaderForm_UseRegex {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string Txt_LogsReaderForm_Working {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern &quot;{0}&quot; is incorrect for use as regular expression! Please check..
        /// </summary>
        internal static string Txt_LogsReaderPerformer_IncorrectSearchPattern {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_IncorrectSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files logs found.
        /// </summary>
        internal static string Txt_LogsReaderPerformer_NoFilesLogsFound {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_NoFilesLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current session already completed!.
        /// </summary>
        internal static string Txt_LogsReaderPerformer_SessionAlreadyCompleted {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_SessionAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session was stopped.
        /// </summary>
        internal static string Txt_LogsReaderPerformer_SessionStopped {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_SessionStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config &quot;{0}&quot; is incorrect! Moved to &quot;{1}&quot;.
        ///
        ///{2}.
        /// </summary>
        internal static string Txt_LRSettings_Deserialize_Ex {
            get {
                return ResourceManager.GetString("Txt_LRSettings_Deserialize_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialize Error.
        /// </summary>
        internal static string Txt_LRSettings_ErrDeserialize {
            get {
                return ResourceManager.GetString("Txt_LRSettings_ErrDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialize Error.
        /// </summary>
        internal static string Txt_LRSettings_ErrSerialize {
            get {
                return ResourceManager.GetString("Txt_LRSettings_ErrSerialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemes names must be unique!.
        /// </summary>
        internal static string Txt_LRSettings_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_LRSettings_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous search value.
        /// </summary>
        internal static string Txt_LRSettings_PreviousSearchComment {
            get {
                return ResourceManager.GetString("Txt_LRSettings_PreviousSearchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save config to path &quot;{0}&quot;.
        ///{1}.
        /// </summary>
        internal static string Txt_LRSettings_Serialize_Ex {
            get {
                return ResourceManager.GetString("Txt_LRSettings_Serialize_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex search is being completed faster. &quot;Encoding&quot; atributte is used when reading log files..
        /// </summary>
        internal static string Txt_LRSettings_UseRegexComment {
            get {
                return ResourceManager.GetString("Txt_LRSettings_UseRegexComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderBy item - &apos;{0}&apos; is incorrect! Please check..
        /// </summary>
        internal static string Txt_LRSettingsScheme_ErrOrderBy {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme &apos;{0}&apos; has incorrect Regex patterns in &apos;TraceParse&apos; node. Please check..
        /// </summary>
        internal static string Txt_LRSettingsScheme_ErrRegex {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns must be unique!.
        /// </summary>
        internal static string Txt_LRSettingsScheme_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory path. File search is being made by all directories..
        /// </summary>
        internal static string Txt_LRSettingsScheme_LogsDirectory {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_LogsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount of threads. If the value is -1 then amount of threads corresponds to the ammount of processing files..
        /// </summary>
        internal static string Txt_LRSettingsScheme_MaxThreads {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_MaxThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount of lines for the found trace. Whole trace must be parsed by the &quot;TraceParse&quot; patterns..
        /// </summary>
        internal static string Txt_LRSettingsScheme_MaxTraceLines {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_MaxTraceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting by fields: &quot;ID&quot;, &quot;Server&quot;, &quot;TraceName&quot;, &quot;Date&quot;, &quot;File&quot;, &quot;FoundLineID&quot; - the number of the line in file by found trace is written with Description. With a comma you can sort the fields, and you can also use the &quot;desc&quot; function..
        /// </summary>
        internal static string Txt_LRSettingsScheme_OrderBy {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit on the count of lines. Reduces RAM usage..
        /// </summary>
        internal static string Txt_LRSettingsScheme_RowsLimit {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_RowsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers for search. Specify with a comma..
        /// </summary>
        internal static string Txt_LRSettingsScheme_Servers {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patterns for reading trace parameters. Selected from top to bottom, from the most accurate to the default. You must use groupings for set data items. Regular expression works only with options Singleline and CultureInvariant. Timeout execution - 10 seconds.
        ///        Optional patterns: StartTraceWith and EndTraceWith - improve search speed because determine the exact verge trace. Options can be used individually, as well as in one setting..
        /// </summary>
        internal static string Txt_LRSettingsScheme_TraceParse {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_TraceParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File types, specify with a comma. A search on the content of the file name, extension included..
        /// </summary>
        internal static string Txt_LRSettingsScheme_Types {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern &quot;{0}&quot; is incorrect!.
        /// </summary>
        internal static string Txt_LRTraceParse_ErrPattern {
            get {
                return ResourceManager.GetString("Txt_LRTraceParse_ErrPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load schema &quot;{0}&quot;
        ///{1}.
        /// </summary>
        internal static string Txt_Main_ErrLoadScheme {
            get {
                return ResourceManager.GetString("Txt_Main_ErrLoadScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load scheme.
        /// </summary>
        internal static string Txt_Main_LoadScheme {
            get {
                return ResourceManager.GetString("Txt_Main_LoadScheme", resourceCulture);
            }
        }
    }
}
