<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://bs.nvg.ru/schemas/PayPerDay/152/1" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" targetNamespace="http://bs.nvg.ru/schemas/PayPerDay/152/1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://bs.nvg.ru/schemas/PayPerDay/152/1/Imports">
      <xsd:import namespace="http://bs.nvg.ru/schemas/PayPerDay/152/1"  schemaLocation="bs.nvg.ru.schemas.PayPerDay.152.1.xsd"/>
      <xsd:import namespace="http://schemas.microsoft.com/2003/10/Serialization/" schemaLocation="schemas.microsoft.com.2003.10.Serialization.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IChangeProfiles_ChangeCounterProfiles_InputMessage">
    <wsdl:part name="parameters" element="tns:ChangeCounterProfiles" />
  </wsdl:message>
  <wsdl:message name="IChangeProfiles_ChangeCounterProfiles_OutputMessage">
    <wsdl:part name="parameters" element="tns:ChangeCounterProfilesResponse" />
  </wsdl:message>
  <wsdl:message name="IChangeProfiles_ChangeCounterProfiles_ChangeProfileFaultFault_FaultMessage">
    <wsdl:part name="detail" element="tns:ChangeProfileFault" />
  </wsdl:message>
  <wsdl:portType name="IChangeProfiles">
    <wsdl:operation name="ChangeCounterProfiles">
      <wsdl:input wsaw:Action="http://bs.nvg.ru/schemas/PayPerDay/152/1/IChangeProfiles/ChangeCounterProfiles" message="tns:IChangeProfiles_ChangeCounterProfiles_InputMessage" />
      <wsdl:output wsaw:Action="http://bs.nvg.ru/schemas/PayPerDay/152/1/IChangeProfiles/ChangeCounterProfilesResponse" message="tns:IChangeProfiles_ChangeCounterProfiles_OutputMessage" />
      <wsdl:fault wsaw:Action="http://bs.nvg.ru/schemas/PayPerDay/152/1/IChangeProfiles/ChangeCounterProfilesChangeProfileFaultFault" name="ChangeProfileFaultFault" message="tns:IChangeProfiles_ChangeCounterProfiles_ChangeProfileFaultFault_FaultMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="DefaultBinding_IChangeProfiles" type="tns:IChangeProfiles">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="ChangeCounterProfiles">
      <soap:operation soapAction="http://bs.nvg.ru/schemas/PayPerDay/152/1/IChangeProfiles/ChangeCounterProfiles" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ChangeProfileFaultFault">
        <soap:fault name="ChangeProfileFaultFault" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ChangeProfilesService">
    <wsdl:port name="ChangeProfilesServicePort" binding="tns:DefaultBinding_IChangeProfiles">
      <soap:address location="http://localhost:2437"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>