//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogsReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogsReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по полю Date.
        /// </summary>
        internal static string Form_DateFilterComment {
            get {
                return ResourceManager.GetString("Form_DateFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по полю Message на совпадение. Опция отключается если значение пустое. Несколько фильтров необходимо указать через запятную..
        /// </summary>
        internal static string Form_MessageFilterComment {
            get {
                return ResourceManager.GetString("Form_MessageFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по полю Trace на совпадение. Опция отключается если значение пустое. Несколько фильтров необходимо указать через запятную..
        /// </summary>
        internal static string Form_TraceNameLikeComment {
            get {
                return ResourceManager.GetString("Form_TraceNameLikeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по полю Trace на несовпадение. Опция отключается если значение пустое. Несколько фильтров необходимо указать через запятную..
        /// </summary>
        internal static string Form_TraceNameNotLikeComment {
            get {
                return ResourceManager.GetString("Form_TraceNameNotLikeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config &apos;{0}&apos; is incorrect! Moved to &apos;{1}&apos;.
        ///
        ///{2}.
        /// </summary>
        internal static string LRSettings_Deserialize_Ex {
            get {
                return ResourceManager.GetString("LRSettings_Deserialize_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущее значение поиска. .
        /// </summary>
        internal static string LRSettings_PreviousSearchComment {
            get {
                return ResourceManager.GetString("LRSettings_PreviousSearchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save config to path=[{0}].
        ///{1}.
        /// </summary>
        internal static string LRSettings_Serialize_Ex {
            get {
                return ResourceManager.GetString("LRSettings_Serialize_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по регулярному выражению выполняется быстрее..
        /// </summary>
        internal static string LRSettings_UseRegexComment {
            get {
                return ResourceManager.GetString("LRSettings_UseRegexComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к папке с логами.
        /// </summary>
        internal static string LRSettingsScheme_LogsDirectoryComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_LogsDirectoryComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное количество потоков. Если установить значение -1, то количество потоков будет соответствовать количеству обрабатываемых файлов..
        /// </summary>
        internal static string LRSettingsScheme_MaxThreadsComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_MaxThreadsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное количество строк для найденного фрагмента. Весь фрагмент должен парсится паттернами из TraceLinePattern. Лишние строки отсекаются..
        /// </summary>
        internal static string LRSettingsScheme_MaxTraceLinesComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_MaxTraceLinesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервера для поиска. Указать через запятую..
        /// </summary>
        internal static string LRSettingsScheme_ServersComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_ServersComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паттерны для считывания параметров. Подбираются сверху вниз, от самого точного, до дефолтного. Обязательные именованные группировки: &lt;Data&gt;; &lt;Trace&gt;; &lt;Message&gt;. Опциональные группировки: &lt;ID&gt;; &lt;Description&gt;. Регулярное выражение работает в Singleline, переводит весь стек лога в одну строку..
        /// </summary>
        internal static string LRSettingsScheme_TraceLinePatternComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_TraceLinePatternComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы файлов. Указать через запятую..
        /// </summary>
        internal static string LRSettingsScheme_TypesComment {
            get {
                return ResourceManager.GetString("LRSettingsScheme_TypesComment", resourceCulture);
            }
        }
    }
}
