//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogsReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogsReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _default {
            get {
                object obj = ResourceManager.GetObject("_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap aborted {
            get {
                object obj = ResourceManager.GetObject("aborted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrowError {
            get {
                object obj = ResourceManager.GetObject("arrowError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrowFiltered {
            get {
                object obj = ResourceManager.GetObject("arrowFiltered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrowTrn {
            get {
                object obj = ResourceManager.GetObject("arrowTrn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap authorization {
            get {
                object obj = ResourceManager.GetObject("authorization", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backError {
            get {
                object obj = ResourceManager.GetObject("backError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backFiltered {
            get {
                object obj = ResourceManager.GetObject("backFiltered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backTrn {
            get {
                object obj = ResourceManager.GetObject("backTrn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bt_play {
            get {
                object obj = ResourceManager.GetObject("bt_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bt_play1 {
            get {
                object obj = ResourceManager.GetObject("bt_play1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clear1 {
            get {
                object obj = ResourceManager.GetObject("clear1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Error1 {
            get {
                object obj = ResourceManager.GetObject("Error1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap failed {
            get {
                object obj = ResourceManager.GetObject("failed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap filtered {
            get {
                object obj = ResourceManager.GetObject("filtered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap finished {
            get {
                object obj = ResourceManager.GetObject("finished", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string LogsReaderForm_alreadyUseFilter_rightPadding {
            get {
                return ResourceManager.GetString("LogsReaderForm_alreadyUseFilter_rightPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90.
        /// </summary>
        public static string LogsReaderForm_btnClear_Width {
            get {
                return ResourceManager.GetString("LogsReaderForm_btnClear_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110.
        /// </summary>
        public static string LogsReaderForm_buttonExport_Width {
            get {
                return ResourceManager.GetString("LogsReaderForm_buttonExport_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string LogsReaderForm_buttonFilter_rightPadding {
            get {
                return ResourceManager.GetString("LogsReaderForm_buttonFilter_rightPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string LogsReaderForm_buttonReset_rightPadding {
            get {
                return ResourceManager.GetString("LogsReaderForm_buttonReset_rightPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap next_arrow {
            get {
                object obj = ResourceManager.GetObject("next_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap notepad_closeAllButThis {
            get {
                object obj = ResourceManager.GetObject("notepad_closeAllButThis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap notepad_closeAllItems {
            get {
                object obj = ResourceManager.GetObject("notepad_closeAllItems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap notepad_closeItem {
            get {
                object obj = ResourceManager.GetObject("notepad_closeItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ok {
            get {
                object obj = ResourceManager.GetObject("Ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap onPause {
            get {
                object obj = ResourceManager.GetObject("onPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ping {
            get {
                object obj = ResourceManager.GetObject("ping", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pingAll {
            get {
                object obj = ResourceManager.GetObject("pingAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap prev_arrow {
            get {
                object obj = ResourceManager.GetObject("prev_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap processing {
            get {
                object obj = ResourceManager.GetObject("processing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap properies {
            get {
                object obj = ResourceManager.GetObject("properies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap reset2 {
            get {
                object obj = ResourceManager.GetObject("reset2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save2 {
            get {
                object obj = ResourceManager.GetObject("save2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap select {
            get {
                object obj = ResourceManager.GetObject("select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap server {
            get {
                object obj = ResourceManager.GetObject("server", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap server_group {
            get {
                object obj = ResourceManager.GetObject("server_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap trn {
            get {
                object obj = ResourceManager.GetObject("trn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Txt_Close {
            get {
                return ResourceManager.GetString("Txt_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All But This.
        /// </summary>
        public static string Txt_CloseAllButThis {
            get {
                return ResourceManager.GetString("Txt_CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Documents.
        /// </summary>
        public static string Txt_CloseAllDocuments {
            get {
                return ResourceManager.GetString("Txt_CloseAllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of end must be greater than date of start.
        /// </summary>
        public static string Txt_DataFilter_ErrDate {
            get {
                return ResourceManager.GetString("Txt_DataFilter_ErrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout while executing pattern: &quot;{0}&quot;.
        ///Timeout: {1}
        ///Input data:
        ///{2}.
        /// </summary>
        public static string Txt_DataTemplate_ErrTimeout {
            get {
                return ResourceManager.GetString("Txt_DataTemplate_ErrTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group names of file types must be unique!.
        /// </summary>
        public static string Txt_FileTypesGroups_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_FileTypesGroups_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders path must be unique!.
        /// </summary>
        public static string Txt_Folders_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_Folders_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with filter.
        /// </summary>
        public static string Txt_Form_AlreadyUseFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_AlreadyUseFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string Txt_Form_ConfigureButton {
            get {
                return ResourceManager.GetString("Txt_Form_ConfigureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Date&quot; filter.
        /// </summary>
        public static string Txt_Form_DateFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_DateFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use options of invariant culture and ignoring the case. When the Regex search option is used, the completion timeout is set in the &apos;@searchingRegExTimeOut&apos; attribute in milliseconds..
        /// </summary>
        public static string Txt_Form_SearchComment {
            get {
                return ResourceManager.GetString("Txt_Form_SearchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Trace&quot; filter to find a matching. Option turns off when value is empty. Several filters have to be listed with a comma. Case is ignored..
        /// </summary>
        public static string Txt_Form_TraceFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_TraceFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;TraceName&quot; filter to find a matching. Option turns off when value is empty. Several filters have to be listed with a comma. Case is ignored..
        /// </summary>
        public static string Txt_Form_TraceNameFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_TraceNameFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options must be selected to perform the search. By mouse right click you can add group(s) of servers, file types, and directories to search..
        /// </summary>
        public static string Txt_Form_trvMainComment {
            get {
                return ResourceManager.GetString("Txt_Form_trvMainComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Add.
        /// </summary>
        public static string Txt_Forms_Add {
            get {
                return ResourceManager.GetString("Txt_Forms_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string Txt_Forms_AddFolder {
            get {
                return ResourceManager.GetString("Txt_Forms_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search will be carried out in the top and all child directories..
        /// </summary>
        public static string Txt_Forms_AddFolderTooltip {
            get {
                return ResourceManager.GetString("Txt_Forms_AddFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        public static string Txt_Forms_AddGroup {
            get {
                return ResourceManager.GetString("Txt_Forms_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All directories.
        /// </summary>
        public static string Txt_Forms_AllDirectories {
            get {
                return ResourceManager.GetString("Txt_Forms_AllDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Cancel.
        /// </summary>
        public static string Txt_Forms_Cancel {
            get {
                return ResourceManager.GetString("Txt_Forms_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Types Group.
        /// </summary>
        public static string Txt_Forms_FileTypesGroup {
            get {
                return ResourceManager.GetString("Txt_Forms_FileTypesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Txt_Forms_Folder {
            get {
                return ResourceManager.GetString("Txt_Forms_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &apos;{0}&apos; is incorrect!.
        /// </summary>
        public static string Txt_Forms_FolderIsIncorrect {
            get {
                return ResourceManager.GetString("Txt_Forms_FolderIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Txt_Forms_Group {
            get {
                return ResourceManager.GetString("Txt_Forms_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups items cannot be Empty!.
        /// </summary>
        public static string Txt_Forms_GroupChildItemIsIncorrect {
            get {
                return ResourceManager.GetString("Txt_Forms_GroupChildItemIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string Txt_Forms_GroupName {
            get {
                return ResourceManager.GetString("Txt_Forms_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name cannot be Empty!.
        /// </summary>
        public static string Txt_Forms_GroupNameIsIncorrect {
            get {
                return ResourceManager.GetString("Txt_Forms_GroupNameIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Txt_Forms_GroupPriority {
            get {
                return ResourceManager.GetString("Txt_Forms_GroupPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      OK.
        /// </summary>
        public static string Txt_Forms_OK {
            get {
                return ResourceManager.GetString("Txt_Forms_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Remove.
        /// </summary>
        public static string Txt_Forms_Remove {
            get {
                return ResourceManager.GetString("Txt_Forms_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Remove All.
        /// </summary>
        public static string Txt_Forms_RemoveAll {
            get {
                return ResourceManager.GetString("Txt_Forms_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Txt_Forms_Server {
            get {
                return ResourceManager.GetString("Txt_Forms_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Group.
        /// </summary>
        public static string Txt_Forms_ServerGroup {
            get {
                return ResourceManager.GetString("Txt_Forms_ServerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about transactions and elapsed execution time.
        /// </summary>
        public static string Txt_Forms_ShowTransactions {
            get {
                return ResourceManager.GetString("Txt_Forms_ShowTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Txt_Global_Back {
            get {
                return ResourceManager.GetString("Txt_Global_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fore.
        /// </summary>
        public static string Txt_Global_Fore {
            get {
                return ResourceManager.GetString("Txt_Global_Fore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to perform a search on several schemes at once. All results are uploaded to the &quot;Global&quot; tab, and the results will be displayed in their own schemes.
        ///When you search again in certain schemes, the results will also be applied in the &quot;Global&quot; tab, if the scheme was originally selected.
        ///When you change the general search settings or filter fields in the &quot;Global&quot; tab - all changes will be made in all of the selected schemes.
        ///Colors schemes are adjustable..
        /// </summary>
        public static string Txt_Global_Info {
            get {
                return ResourceManager.GetString("Txt_Global_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Txt_Global_SelectAll {
            get {
                return ResourceManager.GetString("Txt_Global_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        public static string Txt_Initialization {
            get {
                return ResourceManager.GetString("Txt_Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the server &apos;{0}&apos; is denied. Failed to reach the target path &apos;{1}&apos;..
        /// </summary>
        public static string Txt_LogsReaderForm_AccessDenied {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file type [Ctrl+T].
        /// </summary>
        public static string Txt_LogsReaderForm_AddFileType {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AddFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file type group [Ctrl+H].
        /// </summary>
        public static string Txt_LogsReaderForm_AddFileTypeGroup {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AddFileTypeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add search folder [Ctrl+J].
        /// </summary>
        public static string Txt_LogsReaderForm_AddFolder {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add server [Ctrl+R].
        /// </summary>
        public static string Txt_LogsReaderForm_AddServer {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add server group [Ctrl+G].
        /// </summary>
        public static string Txt_LogsReaderForm_AddServerGroup {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AddServerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear [F6].
        /// </summary>
        public static string Txt_LogsReaderForm_Clear {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color background.
        /// </summary>
        public static string Txt_LogsReaderForm_ColorBack {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_ColorBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coloe foreground.
        /// </summary>
        public static string Txt_LogsReaderForm_ColorFore {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_ColorFore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Txt_LogsReaderForm_Contains {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date value is incorrect.
        /// </summary>
        public static string Txt_LogsReaderForm_DateValueIsIncorrect {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_DateValueIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a universal application for searching and parsing applications logs, as well as convenient viewing..
        /// </summary>
        public static string Txt_LogsReaderForm_Description {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t match by &quot;TraceParse&quot; patterns.
        /// </summary>
        public static string Txt_LogsReaderForm_DoesntMatchByPattern {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_DoesntMatchByPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file &quot;{0}&quot;. {1}.
        /// </summary>
        public static string Txt_LogsReaderForm_ErrExport {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_ErrExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Txt_LogsReaderForm_Export {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export found or filtered data to csv file [Ctrl+S].
        /// </summary>
        public static string Txt_LogsReaderForm_ExportComment {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_ExportComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        public static string Txt_LogsReaderForm_Exporting {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files completed:.
        /// </summary>
        public static string Txt_LogsReaderForm_FilesCompleted_1 {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FilesCompleted_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Txt_LogsReaderForm_FilesCompleted_2 {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FilesCompleted_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Filter [F7].
        /// </summary>
        public static string Txt_LogsReaderForm_Filter {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Types.
        /// </summary>
        public static string Txt_LogsReaderForm_FilteTypes {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FilteTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished in {0}.
        /// </summary>
        public static string Txt_LogsReaderForm_FinishedIn {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FinishedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run filter marked [F1].
        /// </summary>
        public static string Txt_LogsReaderForm_HighlightTxt {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_HighlightTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset marking [SHIFT + F1].
        /// </summary>
        public static string Txt_LogsReaderForm_HighlightTxtOff {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_HighlightTxtOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files searching....
        /// </summary>
        public static string Txt_LogsReaderForm_LogFilesSearching {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_LogFilesSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Txt_LogsReaderForm_LogsFolder {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_LogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Lines.
        /// </summary>
        public static string Txt_LogsReaderForm_MaxLines {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_MaxLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Threads.
        /// </summary>
        public static string Txt_LogsReaderForm_MaxThreads {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_MaxThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next error [F3].
        /// </summary>
        public static string Txt_LogsReaderForm_NextErrButt {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NextErrButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next filtered item [F2].
        /// </summary>
        public static string Txt_LogsReaderForm_NextFilteredButt {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NextFilteredButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next transaction [F4].
        /// </summary>
        public static string Txt_LogsReaderForm_NextTrnButt {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NextTrnButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filter results found.
        /// </summary>
        public static string Txt_LogsReaderForm_NoFilterResultsFound {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NoFilterResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs found.
        /// </summary>
        public static string Txt_LogsReaderForm_NoLogsFound {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NoLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Contains.
        /// </summary>
        public static string Txt_LogsReaderForm_NotContains {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order By.
        /// </summary>
        public static string Txt_LogsReaderForm_OrderBy {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous error [SHIFT+F3].
        /// </summary>
        public static string Txt_LogsReaderForm_PrevErrButt {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_PrevErrButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous filtered item [SHIFT+F2].
        /// </summary>
        public static string Txt_LogsReaderForm_PrevFilteredButt {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_PrevFilteredButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous transaction [SHIFT+F4].
        /// </summary>
        public static string Txt_LogsReaderForm_PrevTrnButt {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_PrevTrnButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties [Ctrl+P].
        /// </summary>
        public static string Txt_LogsReaderForm_Properties {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected [Del].
        /// </summary>
        public static string Txt_LogsReaderForm_RemoveSelected {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Reset [F8].
        /// </summary>
        public static string Txt_LogsReaderForm_Reset {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Limit.
        /// </summary>
        public static string Txt_LogsReaderForm_RowsLimit {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_RowsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search [F5].
        /// </summary>
        public static string Txt_LogsReaderForm_Search {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a search term.
        /// </summary>
        public static string Txt_LogsReaderForm_SearchPatternIsNull {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_SearchPatternIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string Txt_LogsReaderForm_Servers {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop [Esc].
        /// </summary>
        public static string Txt_LogsReaderForm_Stop {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        public static string Txt_LogsReaderForm_Stopping {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to file &quot;{0}&quot;.
        /// </summary>
        public static string Txt_LogsReaderForm_SuccessExport {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_SuccessExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Txt_LogsReaderForm_Types {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use filter when searching.
        /// </summary>
        public static string Txt_LogsReaderForm_UseFilterWhenSearching {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_UseFilterWhenSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Regex.
        /// </summary>
        public static string Txt_LogsReaderForm_UseRegex {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working...{0}.
        /// </summary>
        public static string Txt_LogsReaderForm_Working {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target files not found.
        /// </summary>
        public static string Txt_LogsReaderPerformer_FilesNotInitialized {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_FilesNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern &quot;{0}&quot; is incorrect for use as regular expression! Please check..
        /// </summary>
        public static string Txt_LogsReaderPerformer_IncorrectSearchPattern {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_IncorrectSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files logs found.
        /// </summary>
        public static string Txt_LogsReaderPerformer_NoFilesLogsFound {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_NoFilesLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current session is already completed!.
        /// </summary>
        public static string Txt_LogsReaderPerformer_SessionAlreadyCompleted {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_SessionAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session was stopped.
        /// </summary>
        public static string Txt_LogsReaderPerformer_SessionStopped {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_SessionStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration of custom functions. Used to adjust the displayed data, if this cannot be done by RegEx grouping. Applicable only in the attributes nodes - Pattern and TransactionPattern. Each class must implement the ICustomFunction interface which has only one function &quot;Invoke&quot;. Format: &quot;{custom_function_test(&apos;arg1&apos;, &apos;arg2&apos;, &apos;arg3&apos;, &apos;$1 - test&apos;,&apos;$2&apos;)}&quot;.
        /// </summary>
        public static string Txt_LRSettings_CustomFunctionsComment {
            get {
                return ResourceManager.GetString("Txt_LRSettings_CustomFunctionsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config &quot;{0}&quot; is incorrect! Moved to &quot;{1}&quot;.
        ///
        ///{2}.
        /// </summary>
        public static string Txt_LRSettings_Deserialize_Ex {
            get {
                return ResourceManager.GetString("Txt_LRSettings_Deserialize_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialize Error.
        /// </summary>
        public static string Txt_LRSettings_ErrDeserialize {
            get {
                return ResourceManager.GetString("Txt_LRSettings_ErrDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialize Error.
        /// </summary>
        public static string Txt_LRSettings_ErrSerialize {
            get {
                return ResourceManager.GetString("Txt_LRSettings_ErrSerialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemes names must be unique!.
        /// </summary>
        public static string Txt_LRSettings_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_LRSettings_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous search value.
        /// </summary>
        public static string Txt_LRSettings_PreviousSearchComment {
            get {
                return ResourceManager.GetString("Txt_LRSettings_PreviousSearchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save config to path &quot;{0}&quot;.
        ///{1}.
        /// </summary>
        public static string Txt_LRSettings_Serialize_Ex {
            get {
                return ResourceManager.GetString("Txt_LRSettings_Serialize_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributte &quot;encoding&quot; is used when reading log files. Attribute &quot;cultureList&quot; using when trying to parse string Date from trace, dafault value is empty and for trying to parse multiple cultures set value for example &quot;ru-RU;en-US&quot;. For disable comments in the config file, you should set &quot;disableHintComments&quot; attribute to true..
        /// </summary>
        public static string Txt_LRSettings_SettingsComment {
            get {
                return ResourceManager.GetString("Txt_LRSettings_SettingsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Txt_LRSettings_UseRegexComment {
            get {
                return ResourceManager.GetString("Txt_LRSettings_UseRegexComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading schema &apos;{0}&apos;. Check the settings for &apos;TraceParse\@Pattern&apos; or &apos;TraceParse\@Custom&apos;..
        /// </summary>
        public static string Txt_LRSettingsScheme_ErrMandatory {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme=&quot;{0}&quot; has incorrect node &quot;{1}&quot;. Please check..
        /// </summary>
        public static string Txt_LRSettingsScheme_ErrNode {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderBy item - &apos;{0}&apos; is incorrect! Please check..
        /// </summary>
        public static string Txt_LRSettingsScheme_ErrOrderBy {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;@name&apos; of schemas must not be empty..
        /// </summary>
        public static string Txt_LRSettingsScheme_ErrSchemeName {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrSchemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns must be unique!.
        /// </summary>
        public static string Txt_LRSettingsScheme_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories for search. Enabled option allDirSearching=&quot;true&quot; performs a search in the top and in all child directories..
        /// </summary>
        public static string Txt_LRSettingsScheme_LogsDirectory {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_LogsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount of threads. If the value is -1 then amount of threads corresponds to the ammount of processing files..
        /// </summary>
        public static string Txt_LRSettingsScheme_MaxThreads {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_MaxThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount of lines for trace stack. Whole trace must be parsed by the &quot;TraceParse&quot; patterns. The larger the value, the longer the time allocated to the search processing and affects RAM..
        /// </summary>
        public static string Txt_LRSettingsScheme_MaxTraceLines {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_MaxTraceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed sorting by fields: &quot;ID&quot;, &quot;Server&quot;, &quot;TraceName&quot;, &quot;Date&quot;, &quot;ElapsedSec&quot;, &quot;File&quot;, &quot;Priority&quot;, &quot;FoundLineID&quot;. &quot;FoundLineID&quot; is the line number in the file by found trace, is indicated with Description. With a comma you can sort the fields, and you can also use the &quot;desc&quot; function. &quot;Priority&quot; is what was set when sorting the search order of files..
        /// </summary>
        public static string Txt_LRSettingsScheme_OrderBy {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit on the count of lines. Setting affects RAM..
        /// </summary>
        public static string Txt_LRSettingsScheme_RowsLimit {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_RowsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers for search. Specify with a comma. The &quot;Priority&quot; attribute sets the order in which the search is performed on servers and file types. The value &quot;0&quot; sets the maximum priority..
        /// </summary>
        public static string Txt_LRSettingsScheme_Servers {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &quot;displayDateFormat&quot; sets the display date format. Attribute &quot;culture&quot; is used with the &quot;displayDateFormat&quot; attribute, default value is empty.
        ///        Attribute &quot;transactionsMarkingType&quot; sets the type of marking displayed transactions. Available types - &quot;None&quot;, &quot;Both&quot;, &quot;Color&quot;, &quot;Prompt&quot;.
        ///        &quot;Pattern&quot; nodes are used for parsing and reading trace parameters. It can be used together with the &quot;Custom&quot; setting, and has a higher priority. Selected from top to bottom, from the most accurate to the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Txt_LRSettingsScheme_TraceParse {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_TraceParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File types, specify with a comma. A search on the content of the file name, extension included. The &quot;Priority&quot; attribute sets the order in which the search is performed on servers and file types. The value &quot;0&quot; sets the maximum priority..
        /// </summary>
        public static string Txt_LRSettingsScheme_Types {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern &quot;{0}&quot; is incorrect!.
        /// </summary>
        public static string Txt_LRTraceParse_ErrPattern {
            get {
                return ResourceManager.GetString("Txt_LRTraceParse_ErrPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load schema &quot;{0}&quot;
        ///{1}.
        /// </summary>
        public static string Txt_Main_ErrLoadScheme {
            get {
                return ResourceManager.GetString("Txt_Main_ErrLoadScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load scheme.
        /// </summary>
        public static string Txt_Main_LoadScheme {
            get {
                return ResourceManager.GetString("Txt_Main_LoadScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server group names must be unique!.
        /// </summary>
        public static string Txt_ServerGroups_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_ServerGroups_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Cancel.
        /// </summary>
        public static string TxtConfigureCancel {
            get {
                return ResourceManager.GetString("TxtConfigureCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to checking scheme &quot;{0}&quot;. Please check configuration..
        /// </summary>
        public static string TxtConfigureFailed {
            get {
                return ResourceManager.GetString("TxtConfigureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Reload.
        /// </summary>
        public static string TxtConfigureReload {
            get {
                return ResourceManager.GetString("TxtConfigureReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t change the scheme name  to &quot;{0}&quot;.
        /// </summary>
        public static string TxtConfigureSchemeNameFailed {
            get {
                return ResourceManager.GetString("TxtConfigureSchemeNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Apply.
        /// </summary>
        public static string TxtConfigureSuccess {
            get {
                return ResourceManager.GetString("TxtConfigureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting of scheme is correct. Click &quot;Apply&quot; for the settings to take effect..
        /// </summary>
        public static string TxtConfigureSuccessful {
            get {
                return ResourceManager.GetString("TxtConfigureSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Validate.
        /// </summary>
        public static string TxtConfigureValidate {
            get {
                return ResourceManager.GetString("TxtConfigureValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string TxtReader_BtnAbort {
            get {
                return ResourceManager.GetString("TxtReader_BtnAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string TxtReader_BtnPause {
            get {
                return ResourceManager.GetString("TxtReader_BtnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string TxtReader_BtnResume {
            get {
                return ResourceManager.GetString("TxtReader_BtnResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string TxtReader_CheckBoxes {
            get {
                return ResourceManager.GetString("TxtReader_CheckBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        public static string TxtReader_DgvAbortMinWidth {
            get {
                return ResourceManager.GetString("TxtReader_DgvAbortMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.
        /// </summary>
        public static string TxtReader_DgvCountErrorMatchesMinWidth {
            get {
                return ResourceManager.GetString("TxtReader_DgvCountErrorMatchesMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string TxtReader_DgvCountLastWriteTimeMinWidth {
            get {
                return ResourceManager.GetString("TxtReader_DgvCountLastWriteTimeMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        public static string TxtReader_DgvCountMatchesMinWidth {
            get {
                return ResourceManager.GetString("TxtReader_DgvCountMatchesMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreationTime.
        /// </summary>
        public static string TxtReader_DgvCreationTime {
            get {
                return ResourceManager.GetString("TxtReader_DgvCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string TxtReader_DgvErrors {
            get {
                return ResourceManager.GetString("TxtReader_DgvErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string TxtReader_DgvFile {
            get {
                return ResourceManager.GetString("TxtReader_DgvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string TxtReader_DgvFlow {
            get {
                return ResourceManager.GetString("TxtReader_DgvFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastWrite.
        /// </summary>
        public static string TxtReader_DgvLastWrite {
            get {
                return ResourceManager.GetString("TxtReader_DgvLastWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string TxtReader_DgvMatches {
            get {
                return ResourceManager.GetString("TxtReader_DgvMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string TxtReader_DgvPriority {
            get {
                return ResourceManager.GetString("TxtReader_DgvPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string TxtReader_DgvProcess {
            get {
                return ResourceManager.GetString("TxtReader_DgvProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        public static string TxtReader_DgvProcessMinWidth {
            get {
                return ResourceManager.GetString("TxtReader_DgvProcessMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme.
        /// </summary>
        public static string TxtReader_DgvScheme {
            get {
                return ResourceManager.GetString("TxtReader_DgvScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string TxtReader_DgvSize {
            get {
                return ResourceManager.GetString("TxtReader_DgvSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TxtReader_DgvStatus {
            get {
                return ResourceManager.GetString("TxtReader_DgvStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        public static string TxtReader_DgvStatusMinWidth {
            get {
                return ResourceManager.GetString("TxtReader_DgvStatusMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThreadID.
        /// </summary>
        public static string TxtReader_DgvThreadID {
            get {
                return ResourceManager.GetString("TxtReader_DgvThreadID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        public static string TxtReader_StatusAborted {
            get {
                return ResourceManager.GetString("TxtReader_StatusAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string TxtReader_StatusFailed {
            get {
                return ResourceManager.GetString("TxtReader_StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string TxtReader_StatusFinished {
            get {
                return ResourceManager.GetString("TxtReader_StatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string TxtReader_StatusOnPause {
            get {
                return ResourceManager.GetString("TxtReader_StatusOnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string TxtReader_StatusProcessing {
            get {
                return ResourceManager.GetString("TxtReader_StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string TxtReader_StatusWaiting {
            get {
                return ResourceManager.GetString("TxtReader_StatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap type {
            get {
                object obj = ResourceManager.GetObject("type", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap types_group {
            get {
                object obj = ResourceManager.GetObject("types_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap waiting {
            get {
                object obj = ResourceManager.GetObject("waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
