//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogsReader.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogsReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _default {
            get {
                object obj = ResourceManager.GetObject("_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap authorization {
            get {
                object obj = ResourceManager.GetObject("authorization", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clear1 {
            get {
                object obj = ResourceManager.GetObject("clear1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap error2 {
            get {
                object obj = ResourceManager.GetObject("error2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        public static string LogsReaderForm_alreadyUseFilter_rightPadding {
            get {
                return ResourceManager.GetString("LogsReaderForm_alreadyUseFilter_rightPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 90.
        /// </summary>
        public static string LogsReaderForm_btnClear_Width {
            get {
                return ResourceManager.GetString("LogsReaderForm_btnClear_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 110.
        /// </summary>
        public static string LogsReaderForm_buttonExport_Width {
            get {
                return ResourceManager.GetString("LogsReaderForm_buttonExport_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.
        /// </summary>
        public static string LogsReaderForm_buttonFilter_rightPadding {
            get {
                return ResourceManager.GetString("LogsReaderForm_buttonFilter_rightPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.
        /// </summary>
        public static string LogsReaderForm_buttonReset_rightPadding {
            get {
                return ResourceManager.GetString("LogsReaderForm_buttonReset_rightPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap next_2 {
            get {
                object obj = ResourceManager.GetObject("next_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap notepad_closeAllButThis {
            get {
                object obj = ResourceManager.GetObject("notepad_closeAllButThis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap notepad_closeAllItems {
            get {
                object obj = ResourceManager.GetObject("notepad_closeAllItems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap notepad_closeItem {
            get {
                object obj = ResourceManager.GetObject("notepad_closeItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ok {
            get {
                object obj = ResourceManager.GetObject("Ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ping {
            get {
                object obj = ResourceManager.GetObject("ping", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pingAll {
            get {
                object obj = ResourceManager.GetObject("pingAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap previous_2 {
            get {
                object obj = ResourceManager.GetObject("previous_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap properies {
            get {
                object obj = ResourceManager.GetObject("properies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap reset2 {
            get {
                object obj = ResourceManager.GetObject("reset2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save2 {
            get {
                object obj = ResourceManager.GetObject("save2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap server {
            get {
                object obj = ResourceManager.GetObject("server", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap server_group {
            get {
                object obj = ResourceManager.GetObject("server_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Txt_Close {
            get {
                return ResourceManager.GetString("Txt_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close All But This.
        /// </summary>
        public static string Txt_CloseAllButThis {
            get {
                return ResourceManager.GetString("Txt_CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close All Documents.
        /// </summary>
        public static string Txt_CloseAllDocuments {
            get {
                return ResourceManager.GetString("Txt_CloseAllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of end must be greater than date of start.
        /// </summary>
        public static string Txt_DataFilter_ErrDate {
            get {
                return ResourceManager.GetString("Txt_DataFilter_ErrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeout while executing pattern: &quot;{0}&quot;.
        ///Timeout: {1}
        ///Input data:
        ///{2}.
        /// </summary>
        public static string Txt_DataTemplate_ErrTimeout {
            get {
                return ResourceManager.GetString("Txt_DataTemplate_ErrTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group names of file types must be unique!.
        /// </summary>
        public static string Txt_FileTypesGroups_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_FileTypesGroups_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folders path must be unique!.
        /// </summary>
        public static string Txt_Folders_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_Folders_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search with filter.
        /// </summary>
        public static string Txt_Form_AlreadyUseFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_AlreadyUseFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Date&quot; filter.
        /// </summary>
        public static string Txt_Form_DateFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_DateFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use options of invariant culture and ignoring the case. When Regex option of  search is used timeout of completing is 1 second..
        /// </summary>
        public static string Txt_Form_SearchComment {
            get {
                return ResourceManager.GetString("Txt_Form_SearchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Trace&quot; filter to find a matching. Option turns off when value is empty. Several filters have to be listed with a comma. Case is ignored..
        /// </summary>
        public static string Txt_Form_TraceFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_TraceFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;TraceName&quot; filter to find a matching. Option turns off when value is empty. Several filters have to be listed with a comma. Case is ignored..
        /// </summary>
        public static string Txt_Form_TraceNameFilterComment {
            get {
                return ResourceManager.GetString("Txt_Form_TraceNameFilterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options must be selected to perform the search. By mouse right click you can add group(s) of servers, file types, and directories to search..
        /// </summary>
        public static string Txt_Form_trvMainComment {
            get {
                return ResourceManager.GetString("Txt_Form_trvMainComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     Add.
        /// </summary>
        public static string Txt_Forms_Add {
            get {
                return ResourceManager.GetString("Txt_Forms_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Folder.
        /// </summary>
        public static string Txt_Forms_AddFolder {
            get {
                return ResourceManager.GetString("Txt_Forms_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search will be carried out in the top and all child directories..
        /// </summary>
        public static string Txt_Forms_AddFolderTooltip {
            get {
                return ResourceManager.GetString("Txt_Forms_AddFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Group.
        /// </summary>
        public static string Txt_Forms_AddGroup {
            get {
                return ResourceManager.GetString("Txt_Forms_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All directories.
        /// </summary>
        public static string Txt_Forms_AllDirectories {
            get {
                return ResourceManager.GetString("Txt_Forms_AllDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на      Cancel.
        /// </summary>
        public static string Txt_Forms_Cancel {
            get {
                return ResourceManager.GetString("Txt_Forms_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Types Group.
        /// </summary>
        public static string Txt_Forms_FileTypesGroup {
            get {
                return ResourceManager.GetString("Txt_Forms_FileTypesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder.
        /// </summary>
        public static string Txt_Forms_Folder {
            get {
                return ResourceManager.GetString("Txt_Forms_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder &apos;{0}&apos; is incorrect!.
        /// </summary>
        public static string Txt_Forms_FolderIsIncorrect {
            get {
                return ResourceManager.GetString("Txt_Forms_FolderIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group.
        /// </summary>
        public static string Txt_Forms_Group {
            get {
                return ResourceManager.GetString("Txt_Forms_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Groups items cannot be Empty!.
        /// </summary>
        public static string Txt_Forms_GroupChildItemIsIncorrect {
            get {
                return ResourceManager.GetString("Txt_Forms_GroupChildItemIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group Name.
        /// </summary>
        public static string Txt_Forms_GroupName {
            get {
                return ResourceManager.GetString("Txt_Forms_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group name cannot be Empty!.
        /// </summary>
        public static string Txt_Forms_GroupNameIsIncorrect {
            get {
                return ResourceManager.GetString("Txt_Forms_GroupNameIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Priority.
        /// </summary>
        public static string Txt_Forms_GroupPriority {
            get {
                return ResourceManager.GetString("Txt_Forms_GroupPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на      OK.
        /// </summary>
        public static string Txt_Forms_OK {
            get {
                return ResourceManager.GetString("Txt_Forms_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на      Remove.
        /// </summary>
        public static string Txt_Forms_Remove {
            get {
                return ResourceManager.GetString("Txt_Forms_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на      Remove All.
        /// </summary>
        public static string Txt_Forms_RemoveAll {
            get {
                return ResourceManager.GetString("Txt_Forms_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server.
        /// </summary>
        public static string Txt_Forms_Server {
            get {
                return ResourceManager.GetString("Txt_Forms_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server Group.
        /// </summary>
        public static string Txt_Forms_ServerGroup {
            get {
                return ResourceManager.GetString("Txt_Forms_ServerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string Txt_Global_Back {
            get {
                return ResourceManager.GetString("Txt_Global_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fore.
        /// </summary>
        public static string Txt_Global_Fore {
            get {
                return ResourceManager.GetString("Txt_Global_Fore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to perform a search on several schemes at once. All results are uploaded to the &quot;Global&quot; tab, and the results will be displayed in their own schemes.
        ///When you search again in certain schemes, the results will also be applied in the &quot;Global&quot; tab, if the scheme was originally selected.
        ///When you change the general search settings or filter fields in the &quot;Global&quot; tab - all changes will be made in all of the selected schemes.
        ///Colors schemes are adjustable..
        /// </summary>
        public static string Txt_Global_Info {
            get {
                return ResourceManager.GetString("Txt_Global_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select All.
        /// </summary>
        public static string Txt_Global_SelectAll {
            get {
                return ResourceManager.GetString("Txt_Global_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initialization.
        /// </summary>
        public static string Txt_Initialization {
            get {
                return ResourceManager.GetString("Txt_Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access to the server &apos;{0}&apos; is denied. Failed to reach the target path &apos;{1}&apos;..
        /// </summary>
        public static string Txt_LogsReaderForm_AccessDenied {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add file type [Ctrl+T].
        /// </summary>
        public static string Txt_LogsReaderForm_AddFileType {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AddFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add file type group [Ctrl+H].
        /// </summary>
        public static string Txt_LogsReaderForm_AddFileTypeGroup {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AddFileTypeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add search folder [Ctrl+J].
        /// </summary>
        public static string Txt_LogsReaderForm_AddFolder {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add server [Ctrl+R].
        /// </summary>
        public static string Txt_LogsReaderForm_AddServer {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add server group [Ctrl+G].
        /// </summary>
        public static string Txt_LogsReaderForm_AddServerGroup {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_AddServerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear [F6].
        /// </summary>
        public static string Txt_LogsReaderForm_Clear {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contains.
        /// </summary>
        public static string Txt_LogsReaderForm_Contains {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date value is incorrect.
        /// </summary>
        public static string Txt_LogsReaderForm_DateValueIsIncorrect {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_DateValueIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is a universal application for searching and parsing applications logs, as well as convenient viewing..
        /// </summary>
        public static string Txt_LogsReaderForm_Description {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Doesn&apos;t match by &quot;TraceParse&quot; patterns.
        /// </summary>
        public static string Txt_LogsReaderForm_DoesntMatchByPattern {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_DoesntMatchByPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to save file &quot;{0}&quot;. {1}.
        /// </summary>
        public static string Txt_LogsReaderForm_ErrExport {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_ErrExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Errors:.
        /// </summary>
        public static string Txt_LogsReaderForm_Error {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export [Ctrl+S].
        /// </summary>
        public static string Txt_LogsReaderForm_Export {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export found or filtered data to csv file.
        /// </summary>
        public static string Txt_LogsReaderForm_ExportComment {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_ExportComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exporting....
        /// </summary>
        public static string Txt_LogsReaderForm_Exporting {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files completed:.
        /// </summary>
        public static string Txt_LogsReaderForm_FilesCompleted_1 {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FilesCompleted_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на of.
        /// </summary>
        public static string Txt_LogsReaderForm_FilesCompleted_2 {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FilesCompleted_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter [F7].
        /// </summary>
        public static string Txt_LogsReaderForm_Filter {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Types.
        /// </summary>
        public static string Txt_LogsReaderForm_FilteTypes {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FilteTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finished in {0}.
        /// </summary>
        public static string Txt_LogsReaderForm_FinishedIn {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_FinishedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log files searching....
        /// </summary>
        public static string Txt_LogsReaderForm_LogFilesSearching {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_LogFilesSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folders.
        /// </summary>
        public static string Txt_LogsReaderForm_LogsFolder {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_LogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max Lines.
        /// </summary>
        public static string Txt_LogsReaderForm_MaxLines {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_MaxLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max Threads.
        /// </summary>
        public static string Txt_LogsReaderForm_MaxThreads {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_MaxThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next error (F3).
        /// </summary>
        public static string Txt_LogsReaderForm_NextErrButt {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NextErrButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No filter results found.
        /// </summary>
        public static string Txt_LogsReaderForm_NoFilterResultsFound {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NoFilterResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No logs found.
        /// </summary>
        public static string Txt_LogsReaderForm_NoLogsFound {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NoLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not Contains.
        /// </summary>
        public static string Txt_LogsReaderForm_NotContains {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_NotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order By.
        /// </summary>
        public static string Txt_LogsReaderForm_OrderBy {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found matches:.
        /// </summary>
        public static string Txt_LogsReaderForm_OverallFound {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_OverallFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous error (SHIFT+F3).
        /// </summary>
        public static string Txt_LogsReaderForm_PrevErrButt {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_PrevErrButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties [Ctrl+P].
        /// </summary>
        public static string Txt_LogsReaderForm_Properties {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove selected [Del].
        /// </summary>
        public static string Txt_LogsReaderForm_RemoveSelected {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset [F8].
        /// </summary>
        public static string Txt_LogsReaderForm_Reset {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rows Limit.
        /// </summary>
        public static string Txt_LogsReaderForm_RowsLimit {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_RowsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search [F5].
        /// </summary>
        public static string Txt_LogsReaderForm_Search {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a search term.
        /// </summary>
        public static string Txt_LogsReaderForm_SearchPatternIsNull {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_SearchPatternIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Servers.
        /// </summary>
        public static string Txt_LogsReaderForm_Servers {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop [Esc].
        /// </summary>
        public static string Txt_LogsReaderForm_Stop {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopping....
        /// </summary>
        public static string Txt_LogsReaderForm_Stopping {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully exported to file &quot;{0}&quot;.
        /// </summary>
        public static string Txt_LogsReaderForm_SuccessExport {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_SuccessExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Types.
        /// </summary>
        public static string Txt_LogsReaderForm_Types {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use filter when searching.
        /// </summary>
        public static string Txt_LogsReaderForm_UseFilterWhenSearching {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_UseFilterWhenSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use Regex.
        /// </summary>
        public static string Txt_LogsReaderForm_UseRegex {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Working...{0}.
        /// </summary>
        public static string Txt_LogsReaderForm_Working {
            get {
                return ResourceManager.GetString("Txt_LogsReaderForm_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target files not found.
        /// </summary>
        public static string Txt_LogsReaderPerformer_FilesNotInitialized {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_FilesNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pattern &quot;{0}&quot; is incorrect for use as regular expression! Please check..
        /// </summary>
        public static string Txt_LogsReaderPerformer_IncorrectSearchPattern {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_IncorrectSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No files logs found.
        /// </summary>
        public static string Txt_LogsReaderPerformer_NoFilesLogsFound {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_NoFilesLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current session is already completed!.
        /// </summary>
        public static string Txt_LogsReaderPerformer_SessionAlreadyCompleted {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_SessionAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Session was stopped.
        /// </summary>
        public static string Txt_LogsReaderPerformer_SessionStopped {
            get {
                return ResourceManager.GetString("Txt_LogsReaderPerformer_SessionStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enumeration of custom functions. Used to adjust the displayed data, if this cannot be done by RegEx grouping. Applicable only in the attributes nodes - Pattern and TransactionPattern. Each class must implement the ICustomFunction interface which has only one function &quot;Invoke&quot;. Format: &quot;{custom_function_test(&apos;arg1&apos;, &apos;arg2&apos;, &apos;arg3&apos;, &apos;$1 - test&apos;,&apos;$2&apos;)}&quot;.
        /// </summary>
        public static string Txt_LRSettings_CustomFunctionsComment {
            get {
                return ResourceManager.GetString("Txt_LRSettings_CustomFunctionsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Config &quot;{0}&quot; is incorrect! Moved to &quot;{1}&quot;.
        ///
        ///{2}.
        /// </summary>
        public static string Txt_LRSettings_Deserialize_Ex {
            get {
                return ResourceManager.GetString("Txt_LRSettings_Deserialize_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deserialize Error.
        /// </summary>
        public static string Txt_LRSettings_ErrDeserialize {
            get {
                return ResourceManager.GetString("Txt_LRSettings_ErrDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Serialize Error.
        /// </summary>
        public static string Txt_LRSettings_ErrSerialize {
            get {
                return ResourceManager.GetString("Txt_LRSettings_ErrSerialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Schemes names must be unique!.
        /// </summary>
        public static string Txt_LRSettings_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_LRSettings_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous search value.
        /// </summary>
        public static string Txt_LRSettings_PreviousSearchComment {
            get {
                return ResourceManager.GetString("Txt_LRSettings_PreviousSearchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to save config to path &quot;{0}&quot;.
        ///{1}.
        /// </summary>
        public static string Txt_LRSettings_Serialize_Ex {
            get {
                return ResourceManager.GetString("Txt_LRSettings_Serialize_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Atributte &quot;encoding&quot; is used when reading log files. Attribute &quot;cultureList&quot; using when trying to parse string Date from trace, dafault value is empty and for trying to parse multiple cultures set value for example &quot;ru-RU;en-US&quot;. For disable comments in the config file, you should set &quot;disableHintComments&quot; attribute to true..
        /// </summary>
        public static string Txt_LRSettings_SettingsComment {
            get {
                return ResourceManager.GetString("Txt_LRSettings_SettingsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regex search is being completed faster..
        /// </summary>
        public static string Txt_LRSettings_UseRegexComment {
            get {
                return ResourceManager.GetString("Txt_LRSettings_UseRegexComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error loading schema &apos;{0}&apos;. Check the settings for &apos;TraceParse\@Pattern&apos; or &apos;TraceParse\@Custom&apos;..
        /// </summary>
        public static string Txt_LRSettingsScheme_ErrMandatory {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scheme=&quot;{0}&quot; has incorrect node &quot;{1}&quot;. Please check..
        /// </summary>
        public static string Txt_LRSettingsScheme_ErrNode {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OrderBy item - &apos;{0}&apos; is incorrect! Please check..
        /// </summary>
        public static string Txt_LRSettingsScheme_ErrOrderBy {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The attribute &apos;@name&apos; of schemas must not be empty..
        /// </summary>
        public static string Txt_LRSettingsScheme_ErrSchemeName {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrSchemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Columns must be unique!.
        /// </summary>
        public static string Txt_LRSettingsScheme_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directories for search. Enabled option allDirSearching=&quot;true&quot; performs a search in the top and in all child directories..
        /// </summary>
        public static string Txt_LRSettingsScheme_LogsDirectory {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_LogsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum amount of threads. If the value is -1 then amount of threads corresponds to the ammount of processing files..
        /// </summary>
        public static string Txt_LRSettingsScheme_MaxThreads {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_MaxThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum amount of lines for trace stack. Whole trace must be parsed by the &quot;TraceParse&quot; patterns..
        /// </summary>
        public static string Txt_LRSettingsScheme_MaxTraceLines {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_MaxTraceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allowed sorting by fields: &quot;ID&quot;, &quot;Server&quot;, &quot;TraceName&quot;, &quot;Date&quot;, &quot;File&quot;, &quot;FoundLineID&quot;. &quot;FoundLineID&quot; is the line number in the file by found trace, is indicated with Description. With a comma you can sort the fields, and you can also use the &quot;desc&quot; function..
        /// </summary>
        public static string Txt_LRSettingsScheme_OrderBy {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The limit on the count of lines. Reduces RAM usage..
        /// </summary>
        public static string Txt_LRSettingsScheme_RowsLimit {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_RowsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Servers for search. Specify with a comma. The &quot;Priority&quot; attribute sets the order in which the search is performed on servers and file types. The value &quot;0&quot; sets the maximum priority..
        /// </summary>
        public static string Txt_LRSettingsScheme_Servers {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attribute &quot;displayDateFormat&quot; sets the display date format. Attribute &quot;culture&quot; is used with the &quot;displayDateFormat&quot; attribute, default value is empty.
        ///        &quot;Pattern&quot; nodes are used for parsing and reading trace parameters. It can be used together with the &quot;Custom&quot; setting, and has a higher priority. Selected from top to bottom, from the most accurate to the default. To correctly display the results, RegEx groupings must be used in the attributes. Regular expression works only with options Singleline an [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Txt_LRSettingsScheme_TraceParse {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_TraceParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File types, specify with a comma. A search on the content of the file name, extension included. The &quot;Priority&quot; attribute sets the order in which the search is performed on servers and file types. The value &quot;0&quot; sets the maximum priority..
        /// </summary>
        public static string Txt_LRSettingsScheme_Types {
            get {
                return ResourceManager.GetString("Txt_LRSettingsScheme_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pattern &quot;{0}&quot; is incorrect!.
        /// </summary>
        public static string Txt_LRTraceParse_ErrPattern {
            get {
                return ResourceManager.GetString("Txt_LRTraceParse_ErrPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to load schema &quot;{0}&quot;
        ///{1}.
        /// </summary>
        public static string Txt_Main_ErrLoadScheme {
            get {
                return ResourceManager.GetString("Txt_Main_ErrLoadScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load scheme.
        /// </summary>
        public static string Txt_Main_LoadScheme {
            get {
                return ResourceManager.GetString("Txt_Main_LoadScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server group names must be unique!.
        /// </summary>
        public static string Txt_ServerGroups_ErrUnique {
            get {
                return ResourceManager.GetString("Txt_ServerGroups_ErrUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap type {
            get {
                object obj = ResourceManager.GetObject("type", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap types_group {
            get {
                object obj = ResourceManager.GetObject("types_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
