//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmailParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешные.txt.
        /// </summary>
        internal static string COMPLETED_TEXT {
            get {
                return ResourceManager.GetString("COMPLETED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нераспознанные.txt.
        /// </summary>
        internal static string FAILED_TEXT {
            get {
                return ResourceManager.GetString("FAILED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT files|*.txt.
        /// </summary>
        internal static string FILE_FILTER {
            get {
                return ResourceManager.GetString("FILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icons8_____96__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8_____96__1_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string OPEN_TEXT {
            get {
                return ResourceManager.GetString("OPEN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к:.
        /// </summary>
        internal static string PATH_TEXT {
            get {
                return ResourceManager.GetString("PATH_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Parser.
        /// </summary>
        internal static string PROGR_NAME {
            get {
                return ResourceManager.GetString("PROGR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогресс:.
        /// </summary>
        internal static string PROGRESS_TEXT {
            get {
                return ResourceManager.GetString("PROGRESS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлу.
        /// </summary>
        internal static string SEARCH_IN_FILE {
            get {
                return ResourceManager.GetString("SEARCH_IN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папке.
        /// </summary>
        internal static string SEARCH_IN_FOLDER {
            get {
                return ResourceManager.GetString("SEARCH_IN_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус:.
        /// </summary>
        internal static string STATUS_TEXT {
            get {
                return ResourceManager.GetString("STATUS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстовые файлы не найдены в указанном каталоге!.
        /// </summary>
        internal static string TEXT_ERR1 {
            get {
                return ResourceManager.GetString("TEXT_ERR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный файл не найден!.
        /// </summary>
        internal static string TEXT_ERR2 {
            get {
                return ResourceManager.GetString("TEXT_ERR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнить.
        /// </summary>
        internal static string TEXT_START {
            get {
                return ResourceManager.GetString("TEXT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить.
        /// </summary>
        internal static string TEXT_STOP {
            get {
                return ResourceManager.GetString("TEXT_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть Текстовый Файл.
        /// </summary>
        internal static string TITLE_TEXT {
            get {
                return ResourceManager.GetString("TITLE_TEXT", resourceCulture);
            }
        }
    }
}
