//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error when trying commit and pull!.
        /// </summary>
        internal static string ApplicationUpdater_ErrCommitAndPull {
            get {
                return ResourceManager.GetString("ApplicationUpdater_ErrCommitAndPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error when fetching pack of builds!.
        /// </summary>
        internal static string ApplicationUpdater_ErrFetch {
            get {
                return ResourceManager.GetString("ApplicationUpdater_ErrFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exception when get status from server. HttpStatus=[{0:G}] Uri=[{1}].
        /// </summary>
        internal static string ApplicationUpdater_ErrServerGetStatus {
            get {
                return ResourceManager.GetString("ApplicationUpdater_ErrServerGetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check update minutes interval must be more than zero..
        /// </summary>
        internal static string ApplicationUpdater_ErrUpdateInterval {
            get {
                return ResourceManager.GetString("ApplicationUpdater_ErrUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incoming control &apos;{0}&apos; is incorrect..
        /// </summary>
        internal static string ApplicationUpdater_IncorrectControl {
            get {
                return ResourceManager.GetString("ApplicationUpdater_IncorrectControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No builds found for update..
        /// </summary>
        internal static string ApplicationUpdater_NoBuildsFound {
            get {
                return ResourceManager.GetString("ApplicationUpdater_NoBuildsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} does not expect an update. Before update you must stop checking updates..
        /// </summary>
        internal static string ApplicationUpdater_NotExpectedOnChecking {
            get {
                return ResourceManager.GetString("ApplicationUpdater_NotExpectedOnChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your Updater has not received the updates..
        /// </summary>
        internal static string ApplicationUpdater_NotFetched {
            get {
                return ResourceManager.GetString("ApplicationUpdater_NotFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на day.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на days.
        /// </summary>
        internal static string days2 {
            get {
                return ResourceManager.GetString("days2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на days.
        /// </summary>
        internal static string days5 {
            get {
                return ResourceManager.GetString("days5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hour.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hours.
        /// </summary>
        internal static string hours2 {
            get {
                return ResourceManager.GetString("hours2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hours.
        /// </summary>
        internal static string hours5 {
            get {
                return ResourceManager.GetString("hours5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на minute.
        /// </summary>
        internal static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на minutes.
        /// </summary>
        internal static string minutes2 {
            get {
                return ResourceManager.GetString("minutes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на minutes.
        /// </summary>
        internal static string minutes5 {
            get {
                return ResourceManager.GetString("minutes5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на second.
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на seconds.
        /// </summary>
        internal static string seconds2 {
            get {
                return ResourceManager.GetString("seconds2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на seconds.
        /// </summary>
        internal static string seconds5 {
            get {
                return ResourceManager.GetString("seconds5", resourceCulture);
            }
        }
    }
}
