//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when fetching pack of builds.
        /// </summary>
        internal static string ApplicationUpdater_ErrFetch {
            get {
                return ResourceManager.GetString("ApplicationUpdater_ErrFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors when installing updates.
        /// </summary>
        internal static string ApplicationUpdater_ErrInstall {
            get {
                return ResourceManager.GetString("ApplicationUpdater_ErrInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception when get status from server. HttpStatus=[{0:G}] Uri=[{1}].
        /// </summary>
        internal static string ApplicationUpdater_ErrServerGetStatus {
            get {
                return ResourceManager.GetString("ApplicationUpdater_ErrServerGetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check update minutes interval must be more than zero..
        /// </summary>
        internal static string ApplicationUpdater_ErrUpdateInterval {
            get {
                return ResourceManager.GetString("ApplicationUpdater_ErrUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming control &apos;{0}&apos; is incorrect..
        /// </summary>
        internal static string ApplicationUpdater_IncorrectControl {
            get {
                return ResourceManager.GetString("ApplicationUpdater_IncorrectControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No builds found for update..
        /// </summary>
        internal static string ApplicationUpdater_NoBuildsFound {
            get {
                return ResourceManager.GetString("ApplicationUpdater_NoBuildsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not expect an update. Before update you must stop checking updates..
        /// </summary>
        internal static string ApplicationUpdater_NotExpectedOnChecking {
            get {
                return ResourceManager.GetString("ApplicationUpdater_NotExpectedOnChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Updater has not received the updates..
        /// </summary>
        internal static string ApplicationUpdater_NotFetched {
            get {
                return ResourceManager.GetString("ApplicationUpdater_NotFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string days2 {
            get {
                return ResourceManager.GetString("days2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string days5 {
            get {
                return ResourceManager.GetString("days5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory= &quot;{0}&quot; doesn&apos;t exist.
        /// </summary>
        internal static string DirectoryDoesntExist {
            get {
                return ResourceManager.GetString("DirectoryDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory = &quot;{0}&quot; has no one file..
        /// </summary>
        internal static string DirectoryHasNoFiles {
            get {
                return ResourceManager.GetString("DirectoryHasNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; not exist!.
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string hours2 {
            get {
                return ResourceManager.GetString("hours2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string hours5 {
            get {
                return ResourceManager.GetString("hours5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Invalid file location..
        /// </summary>
        internal static string InvalidFileLocation {
            get {
                return ResourceManager.GetString("InvalidFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string minutes2 {
            get {
                return ResourceManager.GetString("minutes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string minutes5 {
            get {
                return ResourceManager.GetString("minutes5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string seconds2 {
            get {
                return ResourceManager.GetString("seconds2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string seconds5 {
            get {
                return ResourceManager.GetString("seconds5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute Commit.
        /// </summary>
        internal static string UnableExecuteCommit {
            get {
                return ResourceManager.GetString("UnableExecuteCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute Pull.
        /// </summary>
        internal static string UnableExecutePull {
            get {
                return ResourceManager.GetString("UnableExecutePull", resourceCulture);
            }
        }
    }
}
