//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPAFilter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPAFilter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file7 {
            get {
                object obj = ResourceManager.GetObject("file7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter6 {
            get {
                object obj = ResourceManager.GetObject("filter6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder2 {
            get {
                object obj = ResourceManager.GetObject("folder2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please filter files.
        /// </summary>
        internal static string Form_GenerateSC_NotFileredROBPOps {
            get {
                return ResourceManager.GetString("Form_GenerateSC_NotFileredROBPOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operations found.
        /// </summary>
        internal static string Form_GenerateSC_NotFoundAnyOperations {
            get {
                return ResourceManager.GetString("Form_GenerateSC_NotFoundAnyOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete selected {0} ?.
        /// </summary>
        internal static string Form_GridView_DeleteSelected {
            get {
                return ResourceManager.GetString("Form_GridView_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration application is incorrect or scenario collisions were found. Please check same instances (host types)..
        /// </summary>
        internal static string Form_GridView_IncorrectConfig {
            get {
                return ResourceManager.GetString("Form_GridView_IncorrectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect ROBP operation.
        /// </summary>
        internal static string Form_GridView_IncorrectROBPOperation {
            get {
                return ResourceManager.GetString("Form_GridView_IncorrectROBPOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscenario.
        /// </summary>
        internal static string Form_GridView_IsSubScenario {
            get {
                return ResourceManager.GetString("Form_GridView_IsSubScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business process doesn&apos;t have service catalog call.
        /// </summary>
        internal static string Form_GridView_NotFoundServiceCatalogCall {
            get {
                return ResourceManager.GetString("Form_GridView_NotFoundServiceCatalogCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario has some commands which don&apos;t exist.
        /// </summary>
        internal static string Form_GridView_NotFoundSomeCommands {
            get {
                return ResourceManager.GetString("Form_GridView_NotFoundSomeCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-scenario has some commands which don&apos;t exist.
        /// </summary>
        internal static string Form_GridView_NotFoundSomeCommandsInSub {
            get {
                return ResourceManager.GetString("Form_GridView_NotFoundSomeCommandsInSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business process has some operations which don&apos;t exist.
        /// </summary>
        internal static string Form_GridView_NotFoundSomeOPs {
            get {
                return ResourceManager.GetString("Form_GridView_NotFoundSomeOPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario for this operation doesn&apos;t exist.
        /// </summary>
        internal static string Form_GridView_NotFoundSomeScenarios {
            get {
                return ResourceManager.GetString("Form_GridView_NotFoundSomeScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row.
        /// </summary>
        internal static string Form_GridView_NotSelectedAnyRows {
            get {
                return ResourceManager.GetString("Form_GridView_NotSelectedAnyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml file is incorrect!.
        /// </summary>
        internal static string Form_GridView_XMLFileIsIncorrect {
            get {
                return ResourceManager.GetString("Form_GridView_XMLFileIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretty print.
        /// </summary>
        internal static string Form_PrintXMLFiles_Button {
            get {
                return ResourceManager.GetString("Form_PrintXMLFiles_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Form_PrintXMLFiles_Cancel {
            get {
                return ResourceManager.GetString("Form_PrintXMLFiles_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some ({0}) errors found:
        ///
        ///{1}.
        /// </summary>
        internal static string Form_PrintXMLFiles_Error {
            get {
                return ResourceManager.GetString("Form_PrintXMLFiles_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to print all {0} xml files?.
        /// </summary>
        internal static string Form_PrintXMLFiles_Question {
            get {
                return ResourceManager.GetString("Form_PrintXMLFiles_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} xml files were printed..
        /// </summary>
        internal static string Form_PrintXMLFiles_Result {
            get {
                return ResourceManager.GetString("Form_PrintXMLFiles_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully completed..
        /// </summary>
        internal static string Form_PrintXMLFiles_Successfully {
            get {
                return ResourceManager.GetString("Form_PrintXMLFiles_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretty print all filtered XML files.
        /// </summary>
        internal static string Form_PrintXMLFiles_ToolTip {
            get {
                return ResourceManager.GetString("Form_PrintXMLFiles_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Service catalog by Operations.
        /// </summary>
        internal static string Form_ToolTip_ButtonGenerateSC {
            get {
                return ResourceManager.GetString("Form_ToolTip_ButtonGenerateSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export folder path.
        /// </summary>
        internal static string Form_ToolTip_ExportSCPath {
            get {
                return ResourceManager.GetString("Form_ToolTip_ExportSCPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all matches by filter.
        /// </summary>
        internal static string Form_ToolTip_FilterButton {
            get {
                return ResourceManager.GetString("Form_ToolTip_FilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file path of RD services for fill CFS description. Columns names and orders must be like:
        ///&apos;{0}&apos;.
        /// </summary>
        internal static string Form_ToolTip_OpenSCXlsx {
            get {
                return ResourceManager.GetString("Form_ToolTip_OpenSCXlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get excel file of RD services for fill CFS description. Columns names and orders must be like:
        ///&apos;{0}&apos;.
        /// </summary>
        internal static string Form_ToolTip_OpenSevExelButton {
            get {
                return ResourceManager.GetString("Form_ToolTip_OpenSevExelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder with Business Processes.
        /// </summary>
        internal static string Form_ToolTip_ProcessesButtonOpen {
            get {
                return ResourceManager.GetString("Form_ToolTip_ProcessesButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder with Operations.
        /// </summary>
        internal static string Form_ToolTip_ROBPOperationButtonOpen {
            get {
                return ResourceManager.GetString("Form_ToolTip_ROBPOperationButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open export folder path.
        /// </summary>
        internal static string Form_ToolTip_RootSCExportPathButton {
            get {
                return ResourceManager.GetString("Form_ToolTip_RootSCExportPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To search for a specified pattern, you can use % symbol. Example: %Assign%.
        /// </summary>
        internal static string Form_ToolTip_SearchPattern {
            get {
                return ResourceManager.GetString("Form_ToolTip_SearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Service catalog file.
        /// </summary>
        internal static string Form_ToolTip_ServiceCatalogOpenButton {
            get {
                return ResourceManager.GetString("Form_ToolTip_ServiceCatalogOpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap generate4 {
            get {
                object obj = ResourceManager.GetObject("generate4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icons8 {
            get {
                object obj = ResourceManager.GetObject("icons8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_minus_20 {
            get {
                object obj = ResourceManager.GetObject("icons8_minus_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_plus_20 {
            get {
                object obj = ResourceManager.GetObject("icons8_plus_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_synchronize_20 {
            get {
                object obj = ResourceManager.GetObject("icons8_synchronize_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xls1 {
            get {
                object obj = ResourceManager.GetObject("xls1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xml8 {
            get {
                object obj = ResourceManager.GetObject("xml8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
